export {default as Loader} from './loader.svg'
export {default as CaretUp} from './caret-up.svg'
export {default as CaretDown} from './caret-down.svg'
export {default as Resize} from './resize.svg'
export {default as AddCircle} from './add-circle-outline.svg'
export {default as CloseCircle} from './close-circle-outline.svg'
